### ISSUE TITLE
using other containers ie ExaBGP, BIRD, etc

### ISSUE THREAD

**Issue by wmclendon** [plajjan/vrnetlab#123]
hi there,

I apologize if this is a dumb question, but documentation I have seen so far is not clear.

I'm hoping to use this tool to test some things we are looking to add (ie BGP flowspec, RTBH), which I think will initially use some open source routing components like ExaBGP and / or BIRD - at least for testing / trying it out.  Does anything special have to be done (ie creating a custom ExaBGP container with some special settings) to get the vr-xcon connector to work with containers created for these services, or does it 'just work'?

I've successfully created and linked together two vMX's.  This project looks really great -- thank you.  Additionally, my vMX instances seem to be working fine so far, running 17.1R1 image.  Interestingly it seemed like ge-0/0/1 mapped to the 3rd interface, rather than the second for my vr-xcon config (ge-0/0/0 still mapped to the first interface).  Not sure if thats normal for vMX or a quirk of 17.1

Thanks,

Will

**Comment by plajjan** [comment]
Apologies for late answer - I just became a dad and have been a tad preoccupied ;)

Not at all a dumb question! You've nailed it with regard to the specialised networking needs. A standard ExaBGP / BIRD / foo container image will assume that it can just talk BGP on the normal network interface. However, vrnetlab comes with its own overlay network so you need to have vr-xcon in there to connect to a router. Naturally, vr-xcon is not available in most docker images so you would have to modify them to put it there. the vr-bgp container is essentially vr-xcon + exabgp, which is what I have been using for CI testing etc.

An alternative would perhaps be to have a setup where you use a standard BGP speaker container image and then a second vr-xcon container to connect it to the router. That would however require that the vr-xcon container is connected to two docker networks, which is possible but not very simple. Docker doesn't support specifying multiple networks on the command line, so instead of a single `docker run ...` command, you would need to:
 * `docker create ...` to "create" the container first
 * `docker network add ...` to add more networks to it
 * ´docker start` to start the already created container
That's a fair bit more convoluted than a single `docker run` command. Perhaps we can let topology-machine, which already has support for outputting the required `docker run ` commands to run a topology, include this in the output so we don't have to think about it...

With regards to vMX; yes, it's quite possible that the interface mapping is quirky in 17.1. I have not personally tried just yet (it's on my todo!) but I know we have had similar issues with older versions and have worked around it - see https://github.com/plajjan/vrnetlab/blob/master/vmx/docker/launch_vmx.py#L192

**Comment by plajjan** [comment]
I'll be closing this as I think I've answered your question. Feel free to re-open or open a new issue if you find something unclear or just want to continue the conversation :)
