### ISSUE TITLE
Can't build image

### ISSUE THREAD

**Issue by tomreitsma** [plajjan/vrnetlab#208]
I'm trying to build a csr file using the following filename: "csr1000v-universalk9.03.15.00.S.155-2.S-std.qcow2".

Do I have an unsupported version or should I rename it?

**Comment by fredsod** [comment]
I think it should work with that image, what kind of error do you get?

**Comment by tomreitsma** [comment]
I've now tried it with a different image name: "csr1000v-universalk9.16.06.06.qcow2"

The error I'm getting is 

```
Makefile:15: warning: overriding commands for target `docker-pre-build'
../makefile.include:18: warning: ignoring old commands for target `docker-pre-build'
for IMAGE in csr1000v-universalk9.16.06.06.qcow2; do \
		echo "Making $IMAGE"; \
		/Applications/Xcode.app/Contents/Developer/usr/bin/make IMAGE=$IMAGE docker-build; \
	done
Making csr1000v-universalk9.16.06.06.qcow2
Makefile:15: warning: overriding commands for target `docker-pre-build'
../makefile.include:18: warning: ignoring old commands for target `docker-pre-build'
rm -f docker/*.qcow2* docker/*.tgz* docker/*.vmdk* docker/*.iso
cat cidfile | xargs --no-run-if-empty docker rm -f
cat: cidfile: No such file or directory
xargs: illegal option -- -
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
             [-L number] [-n number [-x]] [-P maxprocs] [-s size]
             [utility [argument ...]]
make[1]: [docker-pre-build] Error 1 (ignored)
rm cidfile
rm: cidfile: No such file or directory
make[1]: [docker-pre-build] Error 1 (ignored)
ERROR: Incorrect version string (csr1000v-universalk9.16.06.06.qcow2). The regexp for extracting version information is likely incorrect, check the regexp in the Makefile or open an issue at https://github.com/plajjan/vrnetlab/issues/new including the image file name you are using.
make[1]: *** [docker-build-common] Error 1
make: *** [docker-image] Error 2
```

**Comment by fredsod** [comment]
Seems like the regexp that is used for matching version is not working on OSX.

**Comment by plajjan** [comment]
OSX isn't really supported at all, see https://github.com/plajjan/vrnetlab#system-requirements

There are multiple errors in the above message (it would also be useful you included the exact commands you are running and not just the output since we don't really know where it is coming from). @fredsod might be right on the regexp match. Linux typically ships with GNU tools while OS X ships with BSD (based on FreeBSD binaries I think) style tools like sed. We also see there is a problem with xargs that thinks there's an illegal option.

Even if we work past the sed and xargs problems you are still not going to be able to start (or even build in some cases) the virtual routers on OS X. This is due to limitations outside of our control and as the scope of this project does not include writing a new hypervisor for OS X, I will close this issue ;)

I would love to support it (I have a mac too) the day that bhybe/xhyve does nested virtualisation but I think we'll just wait with fixing BSD tool compatibility till that day.

**Comment by tomreitsma** [comment]
I got around it by doing a docker in docker method using this Dockerfile:

```
FROM ubuntu:latest

RUN apt update \
    && apt install -y build-essential docker.io
VOLUME ["/var/run/docker.sock"]
```

Build runner image:

`docker build . -t vrnetlab-builder`

Enter proper Ubuntu space

`docker run -it --rm -v$(pwd)/../:/data/ -v /var/run/docker.sock:/var/run/docker.sock vrnetlab-builder /bin/bash`

It's not ideal but the suggestion that macos isn't supported makes this a workaround.

Cheers!
