### ISSUE TITLE
Regex not matching for SROS

### ISSUE THREAD

**Issue by bmigette** [plajjan/vrnetlab#213]
While building image for sros-vm-14.0.R3.qcow2, got following error
for IMAGE in sros-vm-14.0.R3.qcow2; do \
		echo "Making $IMAGE"; \
		/Library/Developer/CommandLineTools/usr/bin/make IMAGE=$IMAGE docker-build; \
	done
Making sros-vm-14.0.R3.qcow2
rm -f docker/*.qcow2* docker/*.tgz* docker/*.vmdk* docker/*.iso
ERROR: Incorrect version string (sros-vm-14.0.R3.qcow2). The regexp for extracting version information is likely incorrect, check the regexp in the Makefile or open an issue at https://github.com/plajjan/vrnetlab/issues/new including the image file name you are using.
make[1]: *** [docker-build-common] Error 1
make: *** [docker-image] Error 2

**Comment by plajjan** [comment]
So it looks like you are trying to run this on Mac OS X. Did you read the system requirements section? https://github.com/plajjan/vrnetlab#system-requirements

The problem here might come from BSD vs GNU utils but fixing it won't lead to anything working because there's no KVM on macos and so it's just doomed to fail in the end.

Assuming it is indeed on macos, so I'll close this issue. If it's not, feel free to reopen :)
