### ISSUE TITLE
vEOS fails to build with certain release names

### ISSUE THREAD

**Issue by htj** [plajjan/vrnetlab#80]
Hi

Arista uses some slightly weird release number scheme, that the makefile fails on:

htj@pyrite:~/src/vrnetlab/veos$ make 
Makefile:7: warning: overriding recipe for target 'docker-pre-build'
../makefile.include:24: warning: ignoring old recipe for target 'docker-pre-build'
for IMAGE in vEOS-lab-4.17.1.1F.vmdk; do \
	echo "Making $IMAGE"; \
	make IMAGE=$IMAGE docker-build; \
done
Making vEOS-lab-4.17.1.1F.vmdk
make[1]: Entering directory '/home/htj/src/vrnetlab/veos'
Makefile:7: warning: overriding recipe for target 'docker-pre-build'
../makefile.include:24: warning: ignoring old recipe for target 'docker-pre-build'
cp *.iso docker/
ERROR: Incorrect version string
../makefile.include:27: recipe for target 'docker-build' failed
make[1]: *** [docker-build] Error 1
make[1]: Leaving directory '/home/htj/src/vrnetlab/veos'
../makefile.include:18: recipe for target 'docker-image' failed
make: *** [docker-image] Error 2

Here are the file names:

vEOS-lab-4.17.1.1F.vmdk
vEOS-lab-4.17.1F.vmdk

The image builds fine with the latter one, but not with the first one.

**Comment by plajjan** [comment]
Thx for reporting! :D

**Comment by plajjan** [comment]
Btw, please let me know if it works or not ;) and overall just feedback on the vEOS image would be nice since I'm not using it myself..

**Comment by htj** [comment]
vEOS-lab-4.17.1F.vmdk booted fine as seemed to work. Haven't tried interface mapping.

Haven't tried vEOS-lab-4.17.1.1F.vmdk yet.

I got VMX running and realized I need something beefier than my laptop to run a this (3:36 boot time, and 150% idle, wtf :-))

**Comment by plajjan** [comment]
Ok.

The boot time of the vMX sucks right now because it restarts the control plane once. This is just part of how vMX works. The control plane can be used in vRR mode or vMX and so it requires a reboot to change the mode. We could move this part to the build time instead, which would then lengthen build time to like 2 minutes but would cut that off the boot time.

XRv is also slow in booting and I'm not aware of anything that I can do to speed that up :/

I guess 150% CPU is the forwarding plane of the vMX, right?

**Comment by htj** [comment]
Just to confirm, the vEOS-lab-4.17.1.1F.vmdk images build and boots fine after the fix.
